root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "CGO_ENABLED=1 go build -o ./tmp/main -tags noembedspa ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  # full_bin = "DATABASE_DRIVER=sqlite DATABASE_CONNECTIONSTRING='file:bib.db?cache=shared&_fk=1' OIDC_DISCOVERY=http://127.0.0.1:5556/dex OIDC_CLIENTID=example-client OIDC_CLIENTSECRET=sss CORS_ORIGIN=http://localhost:8080 ./tmp/main"
  # full_bin = "DEV_CORS=http://localhost:5555 ./tmp/main"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
