# fly.toml app configuration file generated for bibliograph on 2023-12-31T11:54:10+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bibliograph"
primary_region = "syd"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"
  DATABASE_DRIVER = "sqlite3"
  DATABASE_CONNECTIONSTRING = "file:/db/bib.db?cache=shared&_fk=1"
  OIDC_DISCOVERY = "https://accounts.google.com"
  OIDC_CLIENTID = "883894501608-oi28lipiih2enov57rf4ro3qk4s7nhmp.apps.googleusercontent.com"
  OIDC_REDIRECTURL = "http://bibliograph.fly.dev/auth/callback"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source = "bibliograph"
  destination = "/db"
