// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BooksColumns holds the columns for the "books" table.
	BooksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "author", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
	}
	// BooksTable holds the schema information for the "books" table.
	BooksTable = &schema.Table{
		Name:       "books",
		Columns:    BooksColumns,
		PrimaryKey: []*schema.Column{BooksColumns[0]},
	}
	// BookReferencesColumns holds the columns for the "book_references" table.
	BookReferencesColumns = []*schema.Column{
		{Name: "book_id", Type: field.TypeInt},
		{Name: "referee_id", Type: field.TypeInt},
	}
	// BookReferencesTable holds the schema information for the "book_references" table.
	BookReferencesTable = &schema.Table{
		Name:       "book_references",
		Columns:    BookReferencesColumns,
		PrimaryKey: []*schema.Column{BookReferencesColumns[0], BookReferencesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "book_references_book_id",
				Columns:    []*schema.Column{BookReferencesColumns[0]},
				RefColumns: []*schema.Column{BooksColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "book_references_referee_id",
				Columns:    []*schema.Column{BookReferencesColumns[1]},
				RefColumns: []*schema.Column{BooksColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BooksTable,
		BookReferencesTable,
	}
)

func init() {
	BookReferencesTable.ForeignKeys[0].RefTable = BooksTable
	BookReferencesTable.ForeignKeys[1].RefTable = BooksTable
}
