name: Build and publish Bibliograph
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.18.2
    - run: npm i
      name: Install packages
      working-directory: client
    - run: npm run build
      name: Build frontend
      working-directory: client
    - name: Copy client build
      run: |
        mkdir -p server/client-dist
        cp client/dist/* server/client-dist
    - name: Setup fly
      uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Build and deploy server
      working-directory: server
      run: flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
